baseURL = 'https://XU1hEEE.github.io/basquecake-hai/'
languageCode = 'en-us'
title = 'BasqueCake'
theme = 'PaperMod'

[params]
  env = "production"
  author = "Marina"
  description = "Exploring Human-AI Interaction."
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

  [params.label]
    text = "BasqueCake"
    icon = "logo.png"
    iconHeight = 30

  # [params.assets]
  #   favicon = "favicon.ico"
  #   favicon16x16 = "favicon-16x16.png"
  #   favicon32x32 = "favicon-32x32.png"
  #   apple_touch_icon = "apple-touch-icon.png"
  #   safari_pinned_tab = "safari-pinned-tab.svg"

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "I'm a trainer. I share insights on Human-AI Interaction."
