baseURL = 'https://XU1hEEE.github.io/basquecake-hai/'
languageCode = 'en-us'
title = 'BasqueCake'
theme = 'PaperMod'

[params]
  env = "production"
  author = "Marina"
  description = "Exploring Human-AI Interaction."
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

  disableSpecial1stPost = true

  [params.label]
    text = "BasqueCake"
    icon = "logo1.png"
    iconHeight = 30

  [params.homeInfoParams]
    Title = " Hi ˶˙ᵕ˙ )ﾉﾞ"
    # Content = "I'm a trainer. I share insights on Human-AI Interaction. Open to chats anytime!"
    Content = """
     I'm a trainer.
     I share insights on Human-AI Interaction.
     Open to chats anytime!
    """

  [[params.socialIcons]]
    name = "email"
    url = "mailto: marinaxu25@ucla.edu"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/XU1hEEE"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/yihe-xu-116963332/"


[menus]
  [[menus.main]]
    name = "Posts"
    pageRef = "/posts"
    weight = 20

  [[menus.main]]
    name = "Search"
    pageRef = "/search"
    weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]