baseURL = 'https://XU1hEEE.github.io/basquecake-hai/'
languageCode = 'en-us'
title = "Marina's HAI Recipes"
theme = 'PaperMod'

[params]
  env = "production"
  author = "Marina"
  description = "Exploring Human-AI Interaction."
  mainSections = ["posts"]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = true
  defaultTheme = "auto"
  disableSpecial1stPost = true

  [params.homeInfoParams]
    Title = "Marina's HAI Recipes"
    Content = "I write about human-AI interaction, research workflows, and product ideas with a calm, minimal lens."

  [params.label]
    text = "Marina's HAI Recipes"
    icon = "logo1.png"
    iconHeight = 30

  [[params.socialIcons]]
    name = "email"
    url = "mailto: marinaxu25@ucla.edu"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/XU1hEEE"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/yihe-xu-116963332/"


[menus]
  [[menus.main]]
    name = "Blog"
    pageRef = "/posts"
    weight = 10
  
  [[menus.main]]
    name = "Notes"
    pageRef = "/notes"
    weight = 20

  [[menus.main]]
    name = "Search"
    pageRef = "/search" 
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
